### PR TITLE
Bring back old fire behavior

### PR DESCRIPTION
**Pull request by ceandream**
To bring back the old fire behavior. It was changed in the version 1.9

### CODE REVIEW

**Comment by kernitus** [comment]
What exactly does this change? How fast fire spreads?

**Comment by ceandream** [comment]
If a player ran through fire, it burned immediately. This has been removed in the newer versions. The player must now be in the fire longer to burn. I have now added this functionality again.

**Comment by kernitus** [comment]
Would this not cause entities' fire ticks to be constantly reset for as long as they're being damaged by fire? That is, would the fire ever go out?

**Comment by ceandream** [comment]
There are 2 different types of fire damage, FIRE and FIRE_TICK. FIRE is getting called if an entity is on fire(or is burning), FIRE_TICK is called if the player is on fire(or the FIRE_TICK has been set)

**Comment by kernitus** [comment]
Ah I see - if an entity is damaged by fire while being in it, the DamageCause is FIRE, while if they're damaged by fire while not directly in contact it will be FIRE_TICK.

I have just fixed some inconsistencies with the naming - I would say this module should be called **OldFireDamageDelay**.

I just have a couple of questions before merging - where did you get the information that this feature changed with 1.9, as I don't see it listed on the wiki's changelog?
Furthermore, where did you get the value for the fire ticks?

Thank you for contributing to the plugin.

**Comment by kernitus** [comment]
Ok @ceandream I am merging this now so I can release a new version, but I have disabled the module by default. I would still like the questions in the previous comment answered when possible.

**Pull request merged**
