### PR TITLE
Fix random knockback

### PR DESCRIPTION
**Pull request by MWHunter**
This is the hack I use on LegacyKB and it works fine.  Unsure why bukkit doesn't call the velocity event after the damage event.

### CODE REVIEW

**Comment by kernitus** [comment]
Is this the same issue as #552 ?

**Comment by MWHunter** [comment]
No, this likely fixes https://github.com/kernitus/BukkitOldCombatMechanics/issues/569

**Comment by kernitus** [comment]
Commit caf99eb59e894ba6a143cbcbcf671203128476cb should do this without having to nuke the hashmap every tick, even if there is no damage event. Also I have no idea why you removed the AttackFrequency module there entirely, it has nothing to do with this PR.

**Comment by MWHunter** [comment]
I forgot about this PR so I used that branch like it wasn't attached to anything

**Pull request closed without merging**
