### PR TITLE
Add a module to disable attack sounds

### LINKED ISSUE #407: Disable new attack sounds
Hello
My suggestion is adding a feature that makes you disable the new attacking sound of minecraft 
entity.player.attack.strong
entity.player.attack.sweep
entity.player.attack.nodamage
and so on.

### PR DESCRIPTION
**Pull request by I-Al-Istannen**
## What
This PR adds a simple module that blocks attack sounds.

## Compatibility
Based on the 1.9 - 1.15 jars it *should* work in all versions.

## References / Closes
#407

### CODE REVIEW

**Comment by kernitus** [comment]
Was there not already a part of the plugin that hid the sweep particles?

**Comment by I-Al-Istannen** [comment]
There still *is* a part that hides sweep particles (in the sweep module). I am not sure what you are trying to communicate here.

**Comment by kernitus** [comment]
Sorry, it's just the comments in the ModuleAttackSounds class, it says `A module to disable the sweep attack.` and `Hides sweep particles`

**Comment by I-Al-Istannen** [comment]
Sorry, that was a mistake on my part. I corrected that.

**Pull request merged**
