### PR TITLE
Fixes Memoryleak 

### PR DESCRIPTION
**Pull request by Ytnoos**
Prevent RunnableSeries to stay in memory when putting a new instance into correspondingTasks (GC will never destroy it)

### CODE REVIEW

**Comment by Ytnoos** [comment]
1. If you call _scheduleRestore()_ without canceling and removing an eventual task first, inside _correspondingTasks_, the RunnableSeries instance will disappear from that map because you put a key (UUID) that already exists on that map and the Entry will be replaced. It will stay in RAM forever because the GC just ignores that unusued instance.
2. It just makes sure that if you put something in that map you first remove it correctly, by stopping the tasks.

**Comment by I-Al-Istannen** [comment]
True, if you mean that:
1. It will probably be kept around as the Scheduler keeps a strong reference to the task timer (as it needs to call it again and again). This timer closes over the player instance, keeping it alive. The timer will not be cancelled as the `tryCancel` affects the newly added tasks, not the replaced - but still active - one.  
I hadn't considered that the uncancelled task timer will be kept alive by the craft scheduler.

That is a much deeper problem than just calling the wrong method IMHO.
1. I would add a safeguard in the timer task that checks if the player is still online.
2. The cancel operations of that timer task should probably affect the tasks directly and not whatever is in the map at a given time.
3. Putting entries in the map should be done in a central place to ensure the map is always cleaned up

Maybe there is more I am forgetting?

**Comment by Ytnoos** [comment]
The second step you said is not doable 100% with the system that is present. The task can cancel itself without any reference just from inside the task, so, if you have to stop it outside, you must refer to that map. Honestly, I think creating an object with two tasks, in this case, is a really bad way

**Comment by Rayzr522** [comment]
i'm gonna have to make some changes after this to improve some semantics and state management, but we've come to the consensus to merge this for now. thanks @Ytnoos :)

**Pull request merged**
